### ISSUE TITLE
Requires a scaling control function

### ISSUE THREAD

**Issue by alex13by** [jhj0517/sd-webui-AdvancedLivePortrait#3]
Obviously the display becomes very unfriendly in different resolutions, the face shape will be larger than the entire screen, if you can scale it is very convenient

**Comment by jhj0517** [comment]
Hi @alex13by!
> the face shape will be larger than the entire screen

I'm not sure about the issue, but you mean the UI becomes too big when uploading image?
Can you show me the example screenshot how it looks like?

**Comment by alex13by** [comment]
![1](https://github.com/user-attachments/assets/f52dc44f-2aba-47a6-8beb-84b40259067c)

Images loaded in forge like this are enlarged and cannot be scaled

**Comment by jhj0517** [comment]
@alex13by got it! `max_height` may help.  
That's an very unfortunate bug because it may only happen if `gradio` < 5 and forge forces gradio to 4.x.

**Comment by jhj0517** [comment]
I just found out that `max_height`  doesn't exist in `gradio` 4.4.0 which forge forces to uses.

Originally this shouldn't happen, it's fixed in `gradio` 5.

Since this is a `gradio` 4.4.0 bug and it may take a long time to fix, ( Hope forge update to `gradio` 5 as fast as possible! )

Alternatively you can use the dedicated web ui, since it uses the latest `gradio`: 
https://github.com/jhj0517/AdvancedLivePortrait-WebUI

**Comment by ali0une** [comment]
Hi there.

in [advanced_live_portrait.py:52](https://github.com/jhj0517/sd-webui-AdvancedLivePortrait/blob/68bdcea4c1d50ab6d8ce7a298a36f6fdf3a9d87c/scripts/advanced_live_portrait.py#L52) you can modify the create_block function to set height like this :

`img_ref = gr.Image(label=_("Reference Image"), height=325)`
`img_out = gr.Image(label=_("Output Image"), height=325)`

```
    def create_block(self):
        with self.app as block:
            with self.i18n:
                gr.Markdown(REPO_MARKDOWN, elem_id="md_project")

                with gr.Row():
                    with gr.Column():
                        img_ref = gr.Image(label=_("Reference Image"), height=325)
                with gr.Row():
                    btn_gen = gr.Button("GENERATE", visible=False)
                with gr.Row(equal_height=True):
                    with gr.Column(scale=9):
                        img_out = gr.Image(label=_("Output Image"), height=325)
                    with gr.Column(scale=1):
                        expression_parameters = self.create_parameters()
                        btn_openfolder = gr.Button('📂')
                        with gr.Accordion("Opt in features", visible=False):
                            img_sample = gr.Image()
                            img_motion_link = gr.Image()
                            tb_exp = gr.Textbox()

                params = expression_parameters + [img_ref]
                opt_in_features_params = [img_sample, img_motion_link, tb_exp]

                gr.on(
                    triggers=[param.change for param in params],
                    fn=self.inferencer.edit_expression,
                    inputs=params + opt_in_features_params,
                    outputs=img_out,
                    show_progress="minimal"
                )

                btn_openfolder.click(
                    fn=lambda: self.open_folder(OUTPUTS_DIR), inputs=None, outputs=None
                )

                btn_gen.click(self.inferencer.edit_expression,
                              inputs=params + opt_in_features_params,
                              outputs=img_out)
        return block
```

**Comment by jhj0517** [comment]
@alex13by Thanks!! Fixed `height` to 1000 in #8.  
I don't know why I didn't see it before. I guess this is fixed now, Feel free to re open!

**Comment by ali0une** [comment]
> Fixed `height` to 1000 in #8. I don't know why I didn't see it before. I guess this is fixed now, Feel free to re open!

@jhj0517 1000 is way to much make the fix useless as it's the same as before.
You should lower this value under 500. Something like 400 would be better iMHO.

**Comment by jhj0517** [comment]
@ali0une Yeah, it seems it would be very different value depending on the device.
In my monitor it fits with 1000. Unfortunately this is the bug (the height should be adjusted automatically with `equal_height`, but it doesn't work in `gradio` 4.4.0 which Forge uses. ) with older versions of `gradio`, so I had to manually set the proper specific height value that would be generous to all devices. 

Since 1000 was fit on my monitor, maybe 500 would be appropriate?

**Comment by ali0une** [comment]
Seems this works by setting 50% of the viewport height (50vh) :
```
    def create_block(self):
        with self.app as block:
            with self.i18n:
                gr.Markdown(REPO_MARKDOWN, elem_id="md_project")

                with gr.Row():
                    with gr.Column():
                        img_ref = gr.Image(label=_("Reference Image"), height="50vh")
                with gr.Row():
                    btn_gen = gr.Button("GENERATE", visible=False)
                with gr.Row(equal_height=True):
                    with gr.Column(scale=9):
                        img_out = gr.Image(label=_("Output Image"), height="50vh")
                    with gr.Column(scale=1):
                        expression_parameters = self.create_parameters()
                        btn_openfolder = gr.Button('📂')
                        with gr.Accordion("Opt in features", visible=False):
                            img_sample = gr.Image()
                            img_motion_link = gr.Image()
                            tb_exp = gr.Textbox()

                params = expression_parameters + [img_ref]
                opt_in_features_params = [img_sample, img_motion_link, tb_exp]

                gr.on(
                    triggers=[param.change for param in params],
                    fn=self.inferencer.edit_expression,
                    inputs=params + opt_in_features_params,
                    outputs=img_out,
                    show_progress="minimal"
                )

                btn_openfolder.click(
                    fn=lambda: self.open_folder(OUTPUTS_DIR), inputs=None, outputs=None
                )

                btn_gen.click(self.inferencer.edit_expression,
                              inputs=params + opt_in_features_params,
                              outputs=img_out)
        return block
```
