### ISSUE TITLE
sh: 1: start: not found

### ISSUE THREAD

**Issue by ali0une** [jhj0517/sd-webui-AdvancedLivePortrait#6]
**Which OS are you using?**
 - OS: Debian 12
 - Ui: Forge version: [f2.0.1v1.10.1-previous-613-gf10214e3](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/f10214e358e730b495ce7bfb0edc4846caecf1b2)
 - python: 3.10.6
 - torch: 2.4.1+cu121
 - xformers: N/A
 - gradio: 4.40.0

Following #4 on a Linux box i have this error when i click the blue folder icon:
`sh: 1: start: not found`

The `os.system(f"start {folder_path}")` command in [advanced_live_portrait.py:98](https://github.com/jhj0517/sd-webui-AdvancedLivePortrait/blob/68bdcea4c1d50ab6d8ce7a298a36f6fdf3a9d87c/scripts/advanced_live_portrait.py#L98) is specific to Windows.

The [open_folder](https://github.com/jhj0517/sd-webui-AdvancedLivePortrait/blob/68bdcea4c1d50ab6d8ce7a298a36f6fdf3a9d87c/scripts/advanced_live_portrait.py#L94) function can be fixed like this to support also Linux and Mac :
```
import os
import subprocess
import sys

    @staticmethod
    def open_folder(folder_path: str):
        if not os.path.exists(folder_path):
            os.makedirs(folder_path, exist_ok=True)
            print(f"The directory path {folder_path} has newly created.")
        
        if os.name == 'nt':  # Windows
            os.startfile(folder_path)
        elif os.name == 'posix':  # macOS and Linux
            if sys.platform == 'darwin':  # macOS
                subprocess.Popen(['open', folder_path])
            elif sys.platform.startswith('linux'):  # Linux
                subprocess.Popen(['xdg-open', folder_path])
        else:
            print("Unsupported operating system")
```

**Comment by jhj0517** [comment]
Ah, it makes error on different OS. Thanks!!
Fixed in #7!
